--CAMPANHA
INSERT INTO "public"."campanha" ("id", "descricao") VALUES (1, 'OITAVAS COPA 2018');

--JOGOS
INSERT INTO jogo VALUES (2, 'URUGUAI', 'PORTUGAL', 1);
INSERT INTO jogo VALUES (3, 'FRANCA', 'ARGENTINA', 1);
INSERT INTO jogo VALUES (4, 'BRASIL', 'MEXICO', 1);
INSERT INTO jogo VALUES (5, 'BELGICA', 'JAPAO', 1);
INSERT INTO jogo VALUES (6, 'ESPANHA', 'RUSSIA', 1);
INSERT INTO jogo VALUES (7, 'CROACIA', 'DINAMARCA', 1);
INSERT INTO jogo VALUES (8, 'SUECIA', 'SUICA', 1);
INSERT INTO jogo VALUES (9, 'COLOMBIA', 'INGLATERRA', 1);

--RESULTADOS DOS JOGOS
INSERT INTO placar VALUES (1, 2, 2, 1, NULL);
INSERT INTO placar VALUES (2, 3, 4, 3, NULL);
INSERT INTO placar VALUES (68, 4, 2, 0, NULL);
INSERT INTO placar VALUES (69, 5, 3, 2, NULL);
INSERT INTO placar VALUES (70, 6, 4, 5, NULL);
INSERT INTO placar VALUES (71, 7, 4, 3, NULL);